version: 2
mkdocs:
  configuration: ./mkdocs.yml
  fail_on_warning: true
python:
  # For available versions, see:
  # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-image
  version: 3.7  # Keep in sync with .travis.yml
  install:
    - requirements: ./requirements.txt
    - path: back/
